api_content_path = "api/"
site_root = "docs"
pkg_path = "."
skip_undoc = true
skip_private = false
ssg = "Markdown"
exclude = []

[externals]
builtins = {name = "Python", url = "https://docs.python.org/3/"}

[render.zola]
use_shortcodes = true
